name: github pages

on:
  push:
    branches:
      - master

jobs:

  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true

    - name: Build
      run: hugo --minify

    - name: Prepare tag
      id: prepare_tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG_NAME="${GITHUB_REF##refs/tags/}"
        echo "::set-output name=tag_name::${TAG_NAME}"
        echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

    - name: Deploy
      uses: peaceiris/actions-github-pages@v3.1.6
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # personal_token: ${{ secrets.PERSONAL_TOKEN }}
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        # publish_branch: master
        publish_dir: ./public
        allow_empty_commit: true
        # keep_files: true
        # force_orphan: true
        # user_name: iris
        # user_email: email@peaceiris.com
        # commit_message: ${{ github.event.head_commit.message }}
        # tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
        # tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'

#     - name: Deploy
#       uses: peaceiris/actions-gh-pages@v2
#       # uses: docker://peaceiris/gh-pages:latest
#       # uses: docker://docker.pkg.github.com/peaceiris/actions-gh-pages/action:latest
#       env:
#         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#         # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
#         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         PUBLISH_BRANCH: gh-pages
#         PUBLISH_DIR: ./public
#       with:
#         commitMessage: ${{ github.event.head_commit.message }}
#         # emptyCommits: false
#         # keepFiles: true

#    - name: Deploy (script)
#      env:
#        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
#        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: ./public
#        SCRIPT_MODE: true
#      run: |
#        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
#        bash ./entrypoint.sh

  setup-hugo:
    name: Test for Hugo Setup Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-18.04'
          - 'macos-latest'
          - 'windows-latest'
        hugo-version:
          - 'latest'
          - '0.63.0'
        extended:
          - true
          - false
    steps:

    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ matrix.hugo-version }}
        extended: ${{ matrix.extended }}

    - name: Run hugo version
      run: echo "::set-output name=hugo_version::$(hugo version)"
      id: hugo_version
    
    - name: '${{ steps.hugo_version.outputs.hugo_version }}'
      run: echo '${{ steps.hugo_version.outputs.hugo_version }}'
