name: github pages external

on:
  push:
    branches:
      - master

jobs:

  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.64.0'

    - name: Build
      run: hugo --minify

    - name: Prepare tag
      id: prepare_tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG_NAME="${GITHUB_REF##refs/tags/}"
        echo "::set-output name=tag_name::${TAG_NAME}"
        echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

#     - name: Deploy
#       uses: peaceiris/actions-gh-pages@v2
#       # uses: docker://peaceiris/gh-pages:v2
#       env:
#         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY_EXTERNAL }}
#         # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
#         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         PUBLISH_BRANCH: gh-pages
#         PUBLISH_DIR: ./public
#         EXTERNAL_REPOSITORY: peaceiris/test-hugo-external-repo
#       with:
#         commitMessage: ${{ github.event.head_commit.message }}
#         # emptyCommits: false
#         # keepFiles: true

    - name: Deploy
      uses: peaceiris/actions-github-pages@v3.1.2
      with:
        # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_EXTERNAL }}  # bug
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        # publish_branch: master
        publish_dir: ./public
        external_repository: peaceiris/test-hugo-external-repo
        allow_empty_commit: true
        # keep_files: true
        # force_orphan: true
        # user_name: iris
        # user_email: email@peaceiris.com
        # commit_message: ${{ github.event.head_commit.message }}
        # tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
        # tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'

#    - name: Deploy (script)
#      env:
#        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY_EXTERNAL }}
#        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
#        EXTERNAL_REPOSITORY: peaceiris/test-hugo-external-repo
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: ./public
#        SCRIPT_MODE: true
#      run: |
#        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
#        bash ./entrypoint.sh
