name: github pages external

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.0'

      - name: Build
        run: hugo --minify

      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

#       - run: chmod 000 ./public/sitemap.xml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-2
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_EXTERNAL }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_branch: master
          publish_dir: ./public
          external_repository: peaceiris/test-hugo-external-repo
          destination_dir: public
          allow_empty_commit: true
          # keep_files: true
          # force_orphan: true
          # user_name: iris
          # user_email: email@peaceiris.com
          # commit_message: ${{ github.event.head_commit.message }}
          # tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          # tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
          cname: 'test-hugo-ext.peaceiris.com'
