name: github pages

on:
  push:
    branches:
    - master

jobs:

  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: 'latest'
      # run: sudo snap install hugo

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      # uses: docker://peaceiris/gh-pages:v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      # with:
        # emptyCommits: false
        # keepFiles: true

#    - name: Deploy (script)
#      env:
#        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
#        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: ./public
#        SCRIPT_MODE: true
#      run: |
#        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0-rc2/entrypoint.sh
#        bash ./entrypoint.sh
