name: github pages

on:
  push:
    branches:
    - master

jobs:

  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Setup Hugo
      # uses: peaceiris/actions-hugo@v2.2.0
      uses: peaceiris/actions-hugo@master
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0-rc0
      # uses: docker://peaceiris/gh-pages:v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      # with:
        # emptyCommits: false
        # keepFiles: true
